name: Release
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - uses: actions/setup-node@v2
          with:
            node-version: 14
        - run: yarn install
        # Is it workaround?
        - run: yarn add semantic-release-gitmoji -D
        # I don't wanna create release.config.js to keep repository clean and make it easy to copy this action
        - run: npx semantic-release --plugins "semantic-release-gitmoji","@semantic-release/npm","@semantic-release/github" --dryRun
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
